server:
  host: 47.117.112.114
  port: 5000
  error:
    include-message: always

spring:
  application:
    name: Booker
    version: 1.0.0
    description: Booker is a book recommendation App

  profiles:
    active: dev

  rabbitmq:
    host: 39.103.210.93
    port: 5672
    username: admin
    password: 123456
    virtual-host: /

  datasource:
    url: jdbc:postgresql://47.117.112.114:5432/booker?useUnicode=true&characterEncoding=utf8
    username: postgres
    password: Aliyun@postgres
    platform: postgres
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 64
      auto-commit: true
      idle-timeout: 180000
      max-lifetime: 1800000
      connection-timeout: 60000
      connection-test-query: SELECT 1

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        event:
          merge.entity_copy_observer: allow
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true


  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: Aliyun@redis
    timeout: 6000
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 10
        min-idle: 2

  mail:
    host: smtp.qq.com
    username: 1311895454@qq.com
    password: tiesbtoatlvfjhib
    port: 465
    protocol: smtps
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

swagger:
  title: ${spring.application.name} API Doc
  version: ${spring.application.version}
  description: Descriptions of the main Booker API
  author: Ourselves 团队
  test-host: http://localhost:${server.port}
  controller-path: com.booker.controller